### ISSUE TITLE
Modern Industrialization Book Spam

### ISSUE THREAD

**Issue by lilrichy** [TeamAOF/All-of-Fabric-4#106]
Every time someone dies and respawns they get new copy of the Modern Industrialization book. Its the only book doing this. Don't know if this is a pack issue or mod issue.

![image](https://user-images.githubusercontent.com/8129775/136645063-6301b015-f6b1-4338-962d-a06eaa639754.png)

**Comment by Monster-Zer0** [comment]
Neither. It's enabled.

Just go to your config folder.. find the modern industrialization config file... open it.. change the variable for enabling book on spawn.
