### ISSUE TITLE
biome locator seem to crash the server

### ISSUE THREAD

**Issue by avalitan** [TeamAOF/All-of-Fabric-4#108]
crash log attached:

[crash-2021-10-11_18.55.42-server.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/7330694/crash-2021-10-11_18.55.42-server.txt)

**Comment by kever** [comment]
same to me, fresh install
[crash-2021-10-16_17.18.26-server.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/7357766/crash-2021-10-16_17.18.26-server.txt)

**Comment by Monster-Zer0** [comment]
using natures compass for next update.
