### ISSUE TITLE
[BUG] 1.0.0: "Exception ticking world" causing server infinite crash loop

### ISSUE THREAD

**Issue by Klowes** [TeamAOF/All-of-Fabric-4#113]
Description:
Based on the log it seems Industrial Revolution is ungracefully handling there being a negative quantity of LF in an energy cube.
This is causing my server to go into an infinite crash loop, all backups of my world from before this occurred have been deleted because of the crash loop...

Steps to Reproduce:
- I'm not certain on this but I suspect inputting to AND outputting from an Industrial Revolution energy cube into a single line caused this. It wasn't an immediate crash though after I had done that.

Technical Information:

Minecraft: 1.17.1
Modpack: All of Fabric 4 1.0.0

Logs:
- Server Crash Log: [crash-2021-10-16_08.43.37-server.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/7357608/crash-2021-10-16_08.43.37-server.txt)

Details:
- It is possible this bug can be fixed by updating the version of Industrial Revolution the pack uses. The pack is currently running indrev-1.11.0-alpha.1.jar, however as of y/d it's updated to indrev-1.11.0-alpha.3.jar. It's hard to tell though as the author's commits are less than forthcoming.

**Comment by Klowes** [comment]
If I had to wager a guess Industrial Revolution is ungracefully handling its energy cube having a negative stored LF value.
based on this log.

May have been because I had one of these cubes outputting to the same line that was inputting into it.

**Comment by kever** [comment]
same error like you, updated jar file to indrev-1.11.0-alpha.3.jar and crashlooped fixed, but don't know about sideeffects

**Comment by Klowes** [comment]
@kever alpha 3 didn't work for me. I ended up downloading the source code for the mod and commenting out the thing that was throwing the exception.

**Comment by dandin87** [comment]
> @kever alpha 3 didn't work for me. I ended up downloading the source code for the mod and commenting out the thing that was throwing the exception. And building a new jar

What specifically did you comment out? We have a base on our server causing the crash. Knowing might help the dev make a work around. 1.0.1 Update will be soon. Working on last changes now.

**Comment by Klowes** [comment]
I submitted an Issue to the mod's repo as well, that's basically identical to this. I also poked them in their Discord last night.
One of the Devs said they'd try to look at it today, but there's been no action of the ticket.

**Comment by dandin87** [comment]
He talks with us in our discord a lot. But life and school come first :) He will get to it though, he always comes through.
