### ISSUE TITLE
Recipe collision between Croptopia and Campanion

### ISSUE THREAD

**Issue by novaktually** [TeamAOF/All-of-Fabric-4#114]
The Croptopia recipe for flour and the Campanion recipe for flour are identical: two wheat placed side-by-side in the crafting table. Currently, the recipe yields the Croptopia flour, making the Campanion recipe unattainable.

Using All of Fabric 4 v 1.0.0.

**Comment by css-01** [comment]
Hello, 

Here's a unofficial temporary fix for your problem. 

[example.zip](https://github.com/TeamAOF/All-of-Fabric-4/files/7358353/example.zip)

**Instruction:**
Open the downloaded archive and extract the _example.js_ file in to your modpack folder, exactly: ` kubejs/server_scripts/*here*.`
