### ISSUE TITLE
Dank [BUG]

### ISSUE THREAD

**Issue by AnasJS99** [TeamAOF/All-of-Fabric-4#119]
Hello,

 A bug with the dank causes the game to crash.

 Reproduce prosses:
  -Get a dank.
  -Activate the dank.
  -Get two or more empty buckets "stacked on top of each other".
  -Scoop a bucket of lava.
  -Have fun reopening the game.

 Versions tested on:
   All of Fabric 4 1.0.0
   All of Fabric 4 1.0.1

**Comment by Seegras** [comment]
Same as #125
