### ISSUE TITLE
my game is crashing everytime i try to open my world

### ISSUE THREAD

**Issue by harielcosta** [TeamAOF/All-of-Fabric-4#12]
i updated to 0.0.4 and my world is crashing now
![image](https://user-images.githubusercontent.com/86612450/123653538-9cacbd80-d803-11eb-867d-ae6b6f26dd1b.png)

**Comment by WarriorsMind** [comment]
There's a conflic going on in the area you are in. I don't know what is causing it tho. All i know is that something is that as been put down in you base/area is no conflicting with the updated stuff witch make it crash. I have the same problem with my server where if i go near my base, it crashes. I don't have much, some chest from the charm mod, some industrial machine, a backpack and a waystone. I gues its an issue with one of these mods when they updated the pack

**Comment by harielcosta** [comment]
thanks, man. the problem is the indrev. go to curseforge and download the alpha7
