### ISSUE TITLE
Resource reload failed

### ISSUE THREAD

**Issue by flarefluffsune** [TeamAOF/All-of-Fabric-4#127]
I'm having this issue too, I would like to use a texture pack I enjoy and I keep getting a failure error so it would be nice to know what's going on and why I cannot use a resource pack I want with this pack.

_Originally posted by @flarefluffsune in https://github.com/TeamAOF/All-of-Fabric-4/issues/47#issuecomment-956141885_

**Comment by Monster-Zer0** [comment]
ok, then continue in #47
