### ISSUE TITLE
Croptopia seeds & vegetables/fruits not compatible with Indrev recycler

### ISSUE THREAD

**Issue by jbavay** [TeamAOF/All-of-Fabric-4#128]
Currently only the vegetables & seeds from vanilla are accepted by Indrev recycler.
Would be great/coherent to have seeds/vegetables/fruits from Croptopia also accepted by Indrev recycler.

**Comment by Monster-Zer0** [comment]
@jbavay still issue on latest version?

**Comment by jbavay** [comment]
@Monster-Zer0 don't know if the commit linked ( 
1e1b767 ) is already available in the last version available on CF?

**Comment by Monster-Zer0** [comment]
sorry, getting ahead of myself. it will be fixed in next release

**Comment by jbavay** [comment]
Tested with AOF4-1.1.0 version successfully.

test Scenario :

1 Indrev recycler (with one lazuli creative)
64 onion seeds (from croptopia)
64 Pepper bell (from Croptopia)
64 Kumkat (From Croptopia)
64 Kumkat sapling (From Croptopia)

All were recyclable as expected.

One small remark: the only croptopia that wasn't usable in recycler was the cinnamon sapling.  Which is, I guess totally acceptable since that one is pretty rare and poor chance to be part of any automation with recycler.

**Comment by jbavay** [comment]
@Monster-Zer0 tested in 1.1.0 and working as expected. thanks :)
