### ISSUE TITLE
breaking a barrel from expanded storage deletes it

### ISSUE THREAD

**Issue by Seegras** [TeamAOF/All-of-Fabric-4#130]
Version: 1.0.1

Breaking a iron/gold/diamond barrel from expanded storage deletes it.

**Comment by Kila-Quack-Kila** [comment]
This I suppose would be non-issue related issue https://github.com/FabricMC/fabric/pull/1629

But basically, don't use AIOT or any tools that do not act like a pickaxe/related tool.

**Comment by Monster-Zer0** [comment]
Please submit a log. you can use a pastebin site, or our own at https://paste.alloffabric.com
