### ISSUE TITLE
Mob View in spectator crashing game

### ISSUE THREAD

**Issue by cloudykira** [TeamAOF/All-of-Fabric-4#135]
"A spectator can click on an entity with the attack button, to take its view"
If i try to mob view in spectator (tested with creeper and zombie) game crashes with error
[crash-2021-11-10_21.35.37-client.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/7515120/crash-2021-11-10_21.35.37-client.txt)

**Comment by Monster-Zer0** [comment]
https://paste.alloffabric.com/emodaqadon.yaml   de-obfuscated

looks like an arcanus issue.

**Comment by Monster-Zer0** [comment]
https://github.com/CammiePone/Arcanus/issues/25   was fixed in a newer release of arcanus. 

will be in next version of AoF current (at time of writing this) is 1.0.1 anything beyond that will most likely have this updated version.

**Comment by cloudykira** [comment]
Fixed in latest modpack version (All of Fabric 4 - 1.1.0)
