### ISSUE TITLE
[1.10] Advancements menu clips off screen on Auto UI size

### ISSUE THREAD

**Issue by Pengalu** [TeamAOF/All-of-Fabric-4#138]
Pretty self explanatory, The Advancements window clips off of the screen on certain GUI sizes causing Tech Reborn to not be shown:

![image](https://user-images.githubusercontent.com/72057664/142754969-c5602447-15bc-4f87-8353-5f6740544ca3.png)

I'm not aware if there are any fabric mods yet for this, so for the time being this is more of a suggestion  / enhancement.

**Comment by InFuRiTy** [comment]
The Auto UI also affects large tooltips  that go outside of the screen making it if not impossible really hard to read.
