### ISSUE TITLE
Industrial Smelter does not work

### ISSUE THREAD

**Issue by JBurlison** [TeamAOF/All-of-Fabric-4#141]
Industrial Smelter does not work, it cannot melt any ores you put in it. You can put the ore in but the machine does nothing. 

![image](https://user-images.githubusercontent.com/1290966/143680744-a755ad46-3bc8-4126-971f-8ce4c1d2c91e.png)

**Comment by jbavay** [comment]
Industrial Smelter need purified ore to smelt it. you have it by putting ore (not raw material) into liquid infuser with sulfuric acid.
raw material are probably already multiplied due to fortune so re-multiply them would be too much.
computer rig from indrev or quary retrieve ore not raw material. so I guess, it's to multiply the result of that mining.

**Comment by InFuRiTy** [comment]
> Industrial Smelter need purified ore to smelt it. you have it by putting ore (not raw material) into liquid infuser with sulfuric acid. raw material are probably already multiplied due to fortune so re-multiply them would be too much. computer rig from indrev or quary retrieve ore not raw material. so I guess, it's to multiply the result of that mining.

Yes he's right. Raw ore variants are excluded from almost all ore processing above x2/x3 because they are affected by Fortune upon mining. My guess is that it was made this way to avoid cheesing/abusing this behavior and getting a ridiculous  amount of materials with significantly less work/effort.

**Comment by JBurlison** [comment]
![image](https://user-images.githubusercontent.com/1290966/143688683-4240a712-a3a6-4308-a825-6bc6cf47a6d6.png)

So this wont work, it needs to be mined with the drill that has silk touch

**Comment by jbavay** [comment]
Yeps, it's what we said. it must be ore, not raw material.
And silk touch is not the only possibility. the computer rig of Industrial Revolution will "mine" ore.
Thus you can multiply the result of it. 
Which make sense.
Probably things that are mined by Quarry of MI is also Ore (not raw) and thus could be tripled/quadrupled there.
Note that the ancient debris that are not impacted by fortune can be quadrupled with the same way.

**Comment by JBurlison** [comment]
Awesome thanks so much for everyones help
