### ISSUE TITLE
Modpack not installing: Missing dependency 3381267

### ISSUE THREAD

**Issue by flowercrownjll** [TeamAOF/All-of-Fabric-4#150]
I tried downloading AoF4 but it stopped installing halfway through and popped up with a message that said "Sorry, we can't load this project. Missing dependency: 3381267" I tried restarting cursforge and restarting my computer, but neither of those worked. Any idea what is going on?

**Comment by Chuunkyz** [comment]
use multimc now

**Comment by flowercrownjll** [comment]
> use multimc now

So far so good using multimc, thank you!!
