### ISSUE TITLE
Game crash when scrolling through JEI (Crash at 6/9)

### ISSUE THREAD

**Issue by RALeaf0** [TeamAOF/All-of-Fabric-4#161]
Installed the modpack today with Iris/Sodium.

Steps to reproduce:
Create a new world, open inventory, scroll the JEI pages, the game crash just before page 6 is displayed.

Same thing occured in solo and multiplayer.
Also same error without any shaderpack on.

Hope to play soon

[crash-2022-03-07_21.21.57-client.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/8200641/crash-2022-03-07_21.21.57-client.txt)

**Comment by dandin87** [comment]
You need to add Indium to use Sodium with pretty much any modpack
https://www.curseforge.com/minecraft/mc-mods/indium

**Comment by RALeaf0** [comment]
Adding Indium fixed the problem.

Thanks !
