### ISSUE TITLE
[Feature] Add Fabric Capes mod

### ISSUE THREAD

**Issue by Ectalite** [TeamAOF/All-of-Fabric-4#21]
Hi, 
Could you add the Fabric Capes mod in the next modpack update ?
Thanks !

**Comment by Ectalite** [comment]
And https://www.curseforge.com/minecraft/mc-mods/automated-crafting if it's possible

**Comment by ImAK9** [comment]
TR has just that.

**Comment by Ectalite** [comment]
I saw that Fabric capes was not added ?
