### ISSUE TITLE
Crash issue with mod "Dank Storage Fabric"

### ISSUE THREAD

**Issue by Zoinzibar** [TeamAOF/All-of-Fabric-4#25]
Hello,
The item "dank 3" from the mod "Dank Storage Fabric" crash my game when i right-click with my dank in "Construction mode".

Here is the crash report :
[crash-2021-07-09_12.26.12-client.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/6790639/crash-2021-07-09_12.26.12-client.txt)

**Comment by Oxcidius** [comment]
I also have this issue with a dank 1 in construction mode.
[crash-2021-07-09_16.00.47-client.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/6792279/crash-2021-07-09_16.00.47-client.txt)

**Comment by ImAK9** [comment]
Duplicate of #14
