### ISSUE TITLE
big torch and mob spawner 

### ISSUE THREAD

**Issue by ItsnotFunndy** [TeamAOF/All-of-Fabric-4#3]
I have used a big torch next to my base but I have a skeleton spawner under my base and it does not work whit the big torch

**Comment by dandin87** [comment]
Yes, that is a feature, Big Torch prevents mob spawns based on low light level, but excludes Cursed Dirt and Spawner spawns. For Spawners, and Cursed Dirt really, you can use a Kibe Drawbridge block and fill it with a light source block, like Blockus blaze lantern,  and then attach a lever or other redstone signal to have it extend out however many blocks you put in upto 64. This is a great toggle for any mob farm.
