### ISSUE TITLE
suggestion    enable all structures from mostructures

### ISSUE THREAD

**Issue by minecrafterseppe** [TeamAOF/All-of-Fabric-4#34]
theres some structures disabled in the config files from mostructures
i would ask to enable them

![image](https://user-images.githubusercontent.com/13523046/126363224-df00ca31-6b06-42c2-a2de-50d221286930.png)
![image](https://user-images.githubusercontent.com/13523046/126363271-12a29613-70bc-4155-8a33-422b0e27843c.png)

**Comment by Nyfaria** [comment]
I believe those structures are currently not functioning which is why they are disabled by default.

**Comment by minecrafterseppe** [comment]
just checked closed and open tickets on mostructures github page and i cant find anything other then a few misplaced blocks
wich is not a bug
https://github.com/frqnny/mostructures/issues?q=is%3Aopen+is%3Aissue

**Comment by Nyfaria** [comment]
If you check thr Structures coming in 1.3 you can see at least one of those disabled structures.  Which means it's no implementation/functional yet

https://github.com/frqnny/mostructures/projects/11

**Comment by minecrafterseppe** [comment]
i see ill close the ticket
