### ISSUE TITLE
Quantum Chestplate crashing game when equipped

### ISSUE THREAD

**Issue by BWITTZ** [TeamAOF/All-of-Fabric-4#35]
[crash-2021-07-20_16.06.04-client.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/6850955/crash-2021-07-20_16.06.04-client.txt)

**Comment by minecrafterseppe** [comment]
can confirm happens in creative aswell

**Comment by ImAK9** [comment]
fixed in 0.0.8
