### ISSUE TITLE
Huge Advancements after picking Iron 

### ISSUE THREAD

**Issue by kalinzange** [TeamAOF/All-of-Fabric-4#4]
How to Reproduce:
 1. Create a SinglePlayer New World on Creative
 2. Get an Iron Ingot from Creative
 3. Huge Advancements on the Chat

Launcher: GDLauncher
AOF Verson: 0.0.2

![image](https://user-images.githubusercontent.com/38161086/122472741-e0f4be00-cfb8-11eb-8383-58687d470044.png)

Logs:
[latest.log](https://github.com/TeamAOF/All-of-Fabric-4/files/6673217/latest.log)

**Comment by ImAK9** [comment]
fixed in newer versions
