### ISSUE TITLE
ZEPHYR workbench crashes the puplic AOF4 server

### ISSUE THREAD

**Issue by minecrafterseppe** [TeamAOF/All-of-Fabric-4#42]
when putting a item in the zephyr bench is crshed the server instantly
(not sure whats it called its the crafting table to make elytra stuff)

**Comment by ImAK9** [comment]
A crashlog would be wonderful

**Comment by minecrafterseppe** [comment]
it crashes your server
the one from discord
i dont have acces to those files
(my client does not crash)

**Comment by dandin87** [comment]
I think its the Screen Handler and Network changes from 1.17.1
https://paste.alloffabric.com/ujideyemem.yaml

**Comment by ImAK9** [comment]
fixed in 0.0.8
