### ISSUE TITLE
oak chest variant has no recipies in usage

### ISSUE THREAD

**Issue by minecrafterseppe** [TeamAOF/All-of-Fabric-4#45]
![image](https://user-images.githubusercontent.com/13523046/126999111-f3118df3-4e33-4bd9-a1bc-e62996713846.png)
the oak chest from "expanded storage" crafted by putting a chest in the crafting grid has no valid recipy usages
for example u cant make iron chests with it
either add recipies for it or remove the recipy for the chest in general

**Comment by dandin87** [comment]
First of all, to even get that chest, you have to put a charm or vanilla chest in the crafting grid to get an Expanded Storage Old Chest, then you that in the crafting grid to get that Chest. Irregardless of it not being in the inputs of recipes, all modded chest work with Expanded Storages "Wood to ____ Upgrade" items. So it can in fact turn into an iron chest....... Some people like the different aesthetics of chests. There is zero reason for this to be an issue where we should remove it.....
