### ISSUE TITLE
[feature] add toms simple storage mod

### ISSUE THREAD

**Issue by minecrafterseppe** [TeamAOF/All-of-Fabric-4#46]
https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric
storage is quite hard in this modpack even with expandedstorage mod
it would be helpfull to have this mod to link all chest together into one central terminal
rather then having a massive array of iron double chests
just a suggestion tho

the discord seems to upvoted this mod aswell in suggestions channel

**Comment by athamour1** [comment]
Good point, I think is a necessary addition to the mod pack.
