### ISSUE TITLE
Texture/Resource Packs

### ISSUE THREAD

**Issue by G8temarine** [TeamAOF/All-of-Fabric-4#47]
Does this pack work with them?

 I get a resource reload failed error with everyone I try that is for the correct version of this pack, I know most don't like using them but its nice to have. Do I have to redo something, or reinstall something? When I try to apply one, it does the loading screen, then flashes, then reloads and after that I get the error.

**Comment by flarefluffsune** [comment]
I'm having this issue too, I would like to use a texture pack I enjoy and I keep getting a failure error so it would be nice to know what's going on and why I cannot use a resource pack I want with this pack.

**Comment by Monster-Zer0** [comment]
I need logs

**Comment by flarefluffsune** [comment]
Okay I can get logs, how do I find them because Minecraft doesn't crash or anything it just pops up a toast saying reload failed and goes back to the resource pack menu.

**Comment by flarefluffsune** [comment]
Don't worry I believe I found out how. I snipped the part of the log from pressing "Okay" in the resource pack menu after adding a pack to it reloading.

https://paste.alloffabric.com/zusezapawo.csharp

**Comment by Kila-Quack-Kila** [comment]
Can you try removing.. "iron_door_top_hinge - Copy.json" this should be in your resource pack.

**Comment by flarefluffsune** [comment]
> Can you try removing.. "iron_door_top_hinge - Copy.json" this should be in your resource pack.

Oh damn that worked. I didn't consider that could be the issue because I use the same texture pack with Better Minecraft and it loads without issue.

**Comment by Monster-Zer0** [comment]
they may have some mod or something that ignores resource pack errors.
