### ISSUE TITLE
AOF 4 Crash

### ISSUE THREAD

**Issue by larholl** [TeamAOF/All-of-Fabric-4#57]
Getting a random crash when playing non server AOF4...log attached. Installed and launched via CurseForge Any thoughts suggestions welcome
[crash-2021-08-03_19.20.55-client.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/6927556/crash-2021-08-03_19.20.55-client.txt)

**Comment by dandin87** [comment]
I would update outvoted, as their mob is causing the crash, if it still crashes after that, then I would post the log to their github.
