### ISSUE TITLE
No Dank Storage Recipes

### ISSUE THREAD

**Issue by WonderBreadPriority** [TeamAOF/All-of-Fabric-4#58]
Clicking or "r"ing on the dank storage cubes in REI (or whatever it is now) does not bring up any recipes, and when I try to craft with recipes listed online, it won't craft them. Might be hidden recipes or just uncraftable. Using unaltered latest version of AoF4

**Comment by dandin87** [comment]
0.0.8 Changelog.....
Changes
Disabled everything from Dank Storage (Will be re-enabled when crashes are fixed).
https://github.com/TeamAOF/All-of-Fabric-4/blob/main/CHANGELOG.md
