### ISSUE TITLE
[Update] Better end is outdated and have issues

### ISSUE THREAD

**Issue by ornotermes** [TeamAOF/All-of-Fabric-4#65]
Hi, could you update Better end in the next release?

Some items can't be made in the currently installed version 0.10.5-pre of Better end that comes with 0.0.9, due to an issue that is fixed in 0.11.0-pre https://github.com/paulevsGitch/BetterEnd/issues/256

**Comment by dandin87** [comment]
Mods will be updated with each update...... Better End just happened to update shortly after we released 0.0.9

**Comment by ornotermes** [comment]
Ah, i didn't it was released just 2 days ago, i just saw the message before saying it was known and fixed longar ago. My bad. Thanks for a fun modpack.
