### ISSUE TITLE
add portal gun mod

### ISSUE THREAD

**Issue by pjalsGit** [TeamAOF/All-of-Fabric-4#67]
https://www.curseforge.com/minecraft/mc-mods/portal-gun-fabric

**Comment by irunatbullets** [comment]
The best place to make mod suggestions is in the mod suggestions #discussion channel in https://discord.gg/6rkdm48

This will allow members of the server to vote for your suggestion.

I have added this for you there.

**Comment by pjalsGit** [comment]
welp, i dont have discord lol
