### ISSUE TITLE
Industrial Revolution

### ISSUE THREAD

**Issue by NaiPox** [TeamAOF/All-of-Fabric-4#68]
When attempting to make Output Servo, recipe calls for Industrial Revolution copper nugget. 
When attempting to make said copper nugget, Charm copper nugget is made. 
Charm copper nugget does not result in Output Servo when put in place of Industrial Revolution copper nugget and there appears to be no other way to acquire the Industrial Revolution copper nugget.

**Comment by dandin87** [comment]
This was fixed...... are you on the latest version? 0.0.9?

**Comment by NaiPox** [comment]
> This was fixed...... are you on the latest version? 0.0.9?

I am so sorry. I assumed I had it updating automatically. I was still on version 0.0.5. My mistake, thanks for pointing it out.
