### ISSUE TITLE
No Recipes for Ruby & Sapphire Tools

### ISSUE THREAD

**Issue by SeeJayEmm** [TeamAOF/All-of-Fabric-4#72]
Ruby and sapphire tools from Tech Reborn have no recipes. Cannot be built on survival. Cannot find a configuration option that would enable/disable them.

**Comment by NeoSono1981** [comment]
those recipes are disabled via kubejs. the relevant stuff is in balancing.js

**Comment by SeeJayEmm** [comment]
> 
> 
> those recipes are disabled via kubejs. the relevant stuff is in balancing.js

Thanks!

**Comment by JFMillerUSA** [comment]
There are recipes on my SP, would it resource pack missing?
