### ISSUE TITLE
Crashing (seemingly) Randomly. Description: Rendering entity in world

### ISSUE THREAD

**Issue by originade** [TeamAOF/All-of-Fabric-4#73]
Playing on a server hosted on my PC. My GF and I are getting this error seemingly randomly. I was just standing around when my game crashed. Here is a paste of crash log. 

https://paste.alloffabric.com/pohowazexi.yaml

**Comment by JFMillerUSA** [comment]
Looks like your using to much memory to run server, try 4096MB or 8192MB

**Comment by dandin87** [comment]
> Playing on a server hosted on my PC. My GF and I are getting this error seemingly randomly. I was just standing around when my game crashed. Here is a paste of crash log.
> 
> https://paste.alloffabric.com/pohowazexi.yaml

I have no idea what the guy above is on about.... The error is clearly about Outvoted Barnacle entity, and geckolib. And your server ram is stated as 4GB which is fine. What version of the pack is this? If 0.0.9 I would check if outvoted and/or geckolib have an update, and then update them. If it's before 0.0.9 then update the modpack. I feel like this error may have happened before 0.0.8. I can safely say it does not happen on the public server, which is 0.0.8 with some of the mods updated, one of those being outvoted.

**Comment by originade** [comment]
Everything server wise and client wise is left as default settings. This is pack version 0.0.9. It does look like there are updated versions of Outvoted and geckolib. I will give those an update and see if that helps. The rate of crashes is pretty low, maybe like once or twice over 4-6 hours it seems so this isn't a critical issue

**Comment by originade** [comment]
Still crashing up most up to date versions of geckolib and outvoted. Log here: https://paste.alloffabric.com/onakapodep.yaml

**Comment by greatest-gatsby** [comment]
Outvoted dev suggested disabling Barnacle spawns while they fix the issue. This has completely resolved the crashing for me.

https://github.com/How-Bout-No/Outvoted/issues/67#issuecomment-902898452
