### ISSUE TITLE
Aeterium Hammer un-craftable

### ISSUE THREAD

**Issue by DakATac** [TeamAOF/All-of-Fabric-4#84]
Need an Aeterium Hammer to craft Aeterium hammer head.
![image_2021-09-01_201948](https://user-images.githubusercontent.com/89849630/131766253-15b66b70-2240-442c-a19e-a067de2b0f72.png)
Cant seem to see any other way to obtain other then spawning in.

**Comment by MisterZam** [comment]
Update the latest version of better end forge

**Comment by dandin87** [comment]
> Update the better end forge to the latest version

Ah yes, please update Better End Forge to latest........ Better End you mean? Aka the Fabric version......

**Comment by MisterZam** [comment]
Ah yes better end. I thought "forge" is part of the name of the mod

**Comment by DakATac** [comment]
Alrighty, tyvm will give that a go, much appreciated
