### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by JasimAlrawie** [TeamAOF/All-of-Fabric-4#85]
When i scroll  in REI when i reach point after tech born things it crashes
And crash happen in
Archtechtury , REi  , entity banner,outvoted , golem...

**Comment by dandin87** [comment]
> When i scroll in REI when i reach point after tech born things it crashes
> And crash happen in
> Archtechtury , REi , entity banner,outvoted , golem...

You added Iris or Sodium. Indium is required to use Sodium with most mod packs. Get it at the link below. 
https://modrinth.com/mod/indium/versions

**Comment by JasimAlrawie** [comment]
> > When i scroll in REI when i reach point after tech born things it crashes
> > And crash happen in
> > Archtechtury , REi , entity banner,outvoted , golem...
> 
> You added Iris or Sodium. Indium is required to use Sodium with most mod packs. Get it at the link below.
> https://modrinth.com/mod/indium/versions

Yes i added iris :(

**Comment by JasimAlrawie** [comment]
And no i didnt add indium
