### ISSUE TITLE
GPU Crashing in livestream (OBS)

### ISSUE THREAD

**Issue by dodo42143** [TeamAOF/All-of-Fabric-4#88]
I'm playing modpack livestream, but the game is crashing my video card. When this occurs the screen goes all black, closes the game and the OBS. This also happens off-stream, but sometimes much less than livestream. What to do now?
Will it be incompatibility with AMD? 

Log: [hs_err_pid4896.log](https://github.com/TeamAOF/All-of-Fabric-4/files/7112305/hs_err_pid4896.log)

Video card: Radeon RX 580 Series
Processor: AMD Ryzen Theradripper 2920X
RAM: 2x8 HyperX Fury 2666MHZ
RAM allocation for the game: 6566 MB

**Comment by Nyfaria** [comment]
This is not a modpack issue. Definitely something wrong with your PC, maybe outdated drivers

**Comment by dodo42143** [comment]
I was thinking about that too, what the hell.
