### ISSUE TITLE
Every time my laptop goes into the Lock Screen, the game crashes

### ISSUE THREAD

**Issue by theosib** [TeamAOF/All-of-Fabric-4#94]
I’m using a Mac with Big Sur. When I’m away from the laptop for a while, it’ll put the display to sleep. When I come back, the game has crashed. This doesn’t happen in vanilla.

**Comment by haykam821** [comment]
Please upload a crash log.

**Comment by theosib** [comment]
[crash-2021-09-16_12.55.45-client.txt](https://github.com/TeamAOF/All-of-Fabric-4/files/7188748/crash-2021-09-16_12.55.45-client.txt)
I have three crash reports. They all have a null pointer exception in the same place. Attached is the most recent.

**Comment by theosib** [comment]
I reported the crash for the specific mod here:
https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/issues/260

**Comment by theosib** [comment]
We figured out that the problem is that the modpack is trying to open too many files at once. A bandaid is to raise the maximum number of simultaneously open files. But if that many files are being open at once, there seems to be a more fundamental problem of too many mods opening too many files.

**Comment by Nyfaria** [comment]
Sounds like a Mac Issue. Because Most files mods open are Configs, and that's not a fundamental issue at all.

**Comment by theosib** [comment]
The one thing I can't understand is why this only occurs when the lock screen engages. If this were a general Mac problem, wouldn't the game be crashing randomly? If I disable the lock screen, I can have the game stay up indefinitely. Yes, raising the max file descriptors helped, and that's definitely a flaw with MacOS. But why does the modpack suddenly go and open a whole load of file descriptors just when the lock screen kicks in? The crash is immediate, pretty much the instant the lock screen starts.

**Comment by dandin87** [comment]
Sounds to me more like your mac is going into a sleep state and not just locking the screen.... Anyways, I would try removing the Dynamic FPS mod, as that may be causing the issue. Not sure it has anything to do with file reads...

**Comment by dandin87** [comment]
Scratch that, This is all Xearo's fault....? Have you tried updating Xearo's Miniap and world map? 
I would also report this issue to them, if its still an issue after updated those two mods.

**Comment by theosib** [comment]
I increased the file descriptor limit, system-wide, and that worked around the problem. At some point, I can try reverting it and see if 1.0.0 of AoF4 still crashes under this condition.
