### ISSUE TITLE
Bedrock at Y=0

### ISSUE THREAD

**Issue by henkaa** [TeamAOF/All-of-Fabric-4#96]
Is there a reason for setting Bedrock in the Overworld to Y=0 or is it just a side effect from using Smoother Bedrock?
My guess is that this makes diamond hunting harder? (due to the changed ore generation in 1.17)

I am new to 1.17, hence the many questions :)

**Comment by MisterZam** [comment]
The what? (Meme) 1.17 cave generation and ore distribution is the same as the previous versions. 1.18 is the true cave and cliffs where in you get to go below y=0

**Comment by henkaa** [comment]
My bad. I had not read on completely then :)
